### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by sfc-gh-selee** [cspotcode/tsimportlib#3]
We would like to use this lib, but we can't find a LICENSE file and there's none specified in the package.json. Could you please let us know if we can use the lib and under which license?

**Comment by kbzowski** [comment]
@cspotcode 
+1. 
MIT Would be nice

**Comment by cspotcode** [comment]
Mit is fine, feel free to send a PR with the necessary updates.

**Comment by kbzowski** [comment]
https://github.com/cspotcode/tsimportlib/pull/5
